from enum import Enum

class WEGDEEL(Enum):
    WGD_OV_BAAN = 301
    WGD_OVERWEG = 302
    WGD_SPOORBAAN = 303
    WGD_BAAN_VOOR_VLIEGVERKEER = 304
    WGD_RIJBAAN_AUTOSNELWEG = 305
    WGD_RIJBAAN_AUTOWEG = 306
    WGD_RIJBAAN_REGIONALE_WEG = 311
    WGD_RIJBAAN_REGIONALE_WEG_DREMPEL = 312
    WGD_RIJBAAN_LOKALE_WEG = 314
    WGD_RIJBAAN_LOKALE_WEG_DREMPEL = 315
    WGD_FIETSPAD = 316
    WGD_VOETPAD = 317
    WGD_VOETPAD_OP_TRAP = 318
    WGD_RUITERPAD = 319
    WGD_PARKEERVAK = 321
    WGD_PARKEREN = 330
    WGD_TOEGANGSREGELGEBIED = 340
    WGD_INRIT = 341
    WGD_WOONERF = 343
    WGD_TRANSITIE = 349

class ONDERSTEUNEND_WEGDEEL(Enum):
    OWG_VERKEERSEILAND = 351
    OWG_VERKEERSEILAND_GESLOTEN_VERHARDING = 352
    OWG_VERKEERSEILAND_OPEN_VERHARDING = 353
    OWG_VERKEERSEILAND_HALF_VERHARD = 354
    OWG_VERKEERSEILAND_ONVERHARD = 355
    OWG_VERKEERSEILAND_GROENVOORZIENING = 356
    OWG_VERKEERSEILAND_GROENVOORZIENING_GRAS = 357
    OWG_BERM = 361
    OWG_BERM_GESLOTEN_VERHARDING = 362
    OWG_BERM_OPEN_VERHARDING = 363
    OWG_BERM_HALF_VERHARD = 364
    OWG_BERM_ONVERHARD = 365
    OWG_BERM_GROENVOORZIENING = 366
    OWG_BERM_GROENVOORZIENING_GRAS = 367
    OWG_TRANSITIE = 390
    WGI_WEGMARKERING_INGERICHT = 391
    WGI_WILDROOSTER_INGERICHT = 392
    WGI_ROOSTER_INGERICHT = 393
    WGI_GELEIDECONSTRUCTIE_INGERICHT = 394

class ONBEGROEID_TERREINDEEL(Enum):
    OTD_ERF = 401
    OTD_GESLOTEN_VERHARDING = 402
    OTD_OPEN_VERHARDING = 403
    OTD_HALF_VERHARD = 404
    OTD_ONVERHARD = 430
    OTD_ZAND = 435
    OTD_AFVAL_APART_PLAATS_INGERICHT = 448
    OTD_TRANSITIE = 449

class BEGROEID_TERREINDEEL(Enum):
    BTD_LOOFBOS = 451
    BTD_GEMENGD_BOS = 452
    BTD_NAALDBOS = 454
    BTD_HEIDE = 455
    BTD_STRUIKEN = 456
    BTD_HOUTWAL = 457
    BTD_DUIN = 458
    BTD_GRASLAND_OVERIG = 460
    BTD_MOERAS = 461
    BTD_RIETLAND = 463
    BTD_FRUITTEELT = 470
    BTD_BOOMTEELT = 471
    BTD_GRASLAND_AGRARISCH = 472
    BTD_GROENVOORZIENING = 474
    BTD_TRANSITIE = 480
    WGI_BOOMSPIEGEL_INGERICHT = 491
    VGO_HAAG_INGERICHT = 492
    VGO_NIET_BGT = 493

class WATERDEEL(Enum):
    WTD_WATERLOOP = 511
    WTD_WATERLAKTE = 512
    WTD_GREPPEL_DROGE_SLOOT = 523
    WTD_TRANSITIE = 540

class ONDERSTEUNEND_WATERDEEL(Enum):
    OWT_OEVER_SLOOTKANT = 541
    OWT_TRANSITIE = 549

class GEOBAG(Enum):
    GEOBAG_PAND_GEPLAND = 571
    GEOBAG_PAND_NIEUW = 572
    GEOBAG_PAND_GEWIJZIGD = 573
    GEOBAG_PAND_VERVALLEN = 574
    GEOBAG_VERBLIJFSOBJECT = 575
    GEOBAG_LIGPLAATS = 576
    GEOBAG_STANDPLAATS = 578
    GEOBAG_WOONPLAATS = 579

class OVERIG(Enum):
    BOUWING = 580
    PND_GRONDVLAK_PAND = 590
