# schema_config.py

# Define BGT columns once
BGT_COLUMNS = [
    "type",
    "bgttype",
    "begintijd",
    "lokaalid",
    "hoogtelig",
    "optalud",
    "bronhoud",
    "bgtstatus",
    "bgtfysvkn",
    "plusfysvkn",
    "geometry",
    "fp",
]

from asset_config import AssetType

# Define per-asset GISIB columns only
ASSET_SCHEMAS = {
    AssetType.TERREINDEEL: [
        "guid",
        "objecttype",
        "object_begintijd",
        "geometry",
        "relatieve_hoogteligging",
        "type_object",
        "type_object_plus",
        "onderhoudsplichtige",
        "gbd_buurt_naam",
        "type_beheerder_plus",
    ],
    AssetType.GROENOBJECTEN: [
        "guid",
        "objecttype",
        "object_begintijd",
        "geometry",
        "relatieve_hoogteligging",
        "type_object",
        "type_object_plus",
        "onderhoudsplichtige",
        "gbd_buurt_naam",
        "type_beheerder_plus",
    ],
    AssetType.VERHARDINGEN: [
        "guid",
        "objecttype",
        "opleverdatum",
        "geometry",
        "relatieve_hoogteligging",
        "type_object",
        "type_plus",
        "onderhoudsplichtige",
        "gbd_buurt_naam",
        "type_beheerder_plus",
    ],
}

mappings = {
    AssetType.TERREINDEEL: {
    "id": "ID",
    "guid": "GUID",
    "imgeo_identificatie": "IMGEOID",
    "identificatie": "IDENTIFICATIE",
    "afvoeren": "AFVOEREN",
    "beheerafspraak": "BEHEERAFSPRAAK",
    "type_beheerder": "BEHEERDER",
    "type_beheerder_plus": "BEHEERDER_GEDETAILLEERD",
    "beheergebied": "BEHEERGEBIED",
    "bereikbaarheid": "BEREIKBAARHEID",
    "bewerkingspercentage": "BEWERKINGSPERCENTAGE",
    "breedte": "BREEDTE",
    "gbd_buurt_naam": "BUURT",
    "conditiescore": "CONDITIESCORE",
    "controlefrequentie": "CONTROLEFREQUENTIE",
    "deelsportcomplex": "DEELSPORTCOMPLEX",
    "ecologisch_beheer": "ECOLOGISCH_BEHEREN",
    "type_eigenaar": "EIGENAAR",
    "type_eigenaar_plus": "EIGENAAR_GEDETAILLEERD",
    "gebruiksfunctie": "GEBRUIKSFUNCTIE",
    "brk_gme_naam": "GEMEENTE",
    "jaar_van_aanleg": "JAAR_VAN_AANLEG",
    "knipfrequentie": "KNIPFREQUENTIE",
    "mutatiedatum": "LASTUPDATE",
    "maaifrequentie": "MAAIFREQUENTIE",
    "objecttype": "OBJECTTYPE",
    "onderhoudsplichtige": "ONDERHOUDSPLICHTIGE",
    "op_talud": "OP_TALUD",
    "opleverdatum": "OPLEVERDATUM",
    "percentage_loofbos": "PERCENTAGE_LOOFBOS",
    "risicotoeslag": "RISICOTOESLAG",
    "relatieve_hoogteligging": "RELATIEVE_HOOGTELIGGING",
    "gbd_stadsdeel_naam": "STADSDEEL_OF_KERN",
    "theoretisch_eindjaar": "THEORETISCH_EINDJAAR",
    "type_bewerking": "TYPE_BEWERKING",
    "type_object": "TYPE",
    "type_object_plus_2": "TYPE_EXTRA_GEDETAILLEERD",
    "type_object_plus": "TYPE_GEDETAILLEERD",
    "vaknummer": "VAKNUMMER",
    "object_begin_tijd": "VALID_FROM",
    "object_eind_tijd": "VALID_TILL",
    "verwijderdatum": "VERWIJDERDATUM",
    "gbd_wijk_naam": "WIJK",
    "bag_woonplaats_naam": "WOONPLAATS"
},
AssetType.GROENOBJECTEN: {
    "id": "ID",
    "guid": "GUID",
    "imgeo_identificatie": "IMGEOID",
    "conversie_id": "CONVERSIEID",
    "id_uit_oude_beheerindeling": "ID_UIT_OUDE_BEHEERINDELING",
    "identificatie": "IDENTIFICATIE",
    "aantal_zijden": "AANTAL_ZIJDEN",
    "bollen": "AANWEZIGHEID_BOLLEN",
    "afvoeren": "AFVOEREN",
    "bag_openbare_ruimte_naam": "OPENBARE_RUIMTE",
    "bag_woonplaats_naam": "WOONPLAATS",
    "begin_garantieperiode": "BEGIN_GARANTIEPERIODE",
    "beheerafspraak": "BEHEERAFSPRAAK",
    "type_beheerder": "BEHEERDER",
    "type_beheerder_plus": "BEHEERDER_GEDETAILLEERD",
    "beheergebied": "BEHEERGEBIED",
    "bereikbaarheid": "BEREIKBAARHEID",
    "bewerkingspercentage": "BEWERKINGSPERCENTAGE",
    "breedte": "BREEDTE",
    "breedteklasse_haag": "BREEDTEKLASSE_HAAG",
    "brk_gme_naam": "GEMEENTE",
    "conditiescore": "CONDITIESCORE",
    "controlefrequentie": "CONTROLEFREQUENTIE",
    "deelsportcomplex": "DEELSPORTCOMPLEX",
    "ecologisch_beheer": "ECOLOGISCH_BEHEREN",
    "type_eigenaar": "EIGENAAR",
    "type_eigenaar_plus": "EIGENAAR_GEDETAILLEERD",
    "einde_garantieperiode": "EINDE_GARANTIEPERIODE",
    "gbd_buurt_naam": "BUURT",
    "gbd_stadsdeel_naam": "STADSDEEL_OF_KERN",
    "gbd_wijk_naam": "WIJK",
    "gebruiksfunctie": "GEBRUIKSFUNCTIE",
    "hoogte": "HOOGTE",
    "hoogteklasse_haag": "HOOGTEKLASSE_HAAG",
    "jaar_van_aanleg": "JAAR_VAN_AANLEG",
    "knipfrequentie": "KNIPFREQUENTIE",
    "knipoppervlakte": "KNIPOPPERVLAKTE",
    "mutatiedatum": "LASTUPDATE",
    "lengte": "LENGTE",
    "haagvoet_lengte": "LENGTE_HAAGVOET",
    "maaifrequentie": "MAAIFREQUENTIE",
    "objecttype": "OBJECTTYPE",
    "omtrek": "OMTREK",
    "ondergroei": "ONDERGROEI",
    "onderhoudsplichtige": "ONDERHOUDSPLICHTIGE",
    "op_talud": "OP_TALUD",
    "opleverdatum": "OPLEVERDATUM",
    "haagvoet_oppervlakte": "OPPERVLAKTE_HAAGVOET",
    "relatieve_hoogteligging": "RELATIEVE_HOOGTELIGGING",
    "risicotoeslag": "RISICOTOESLAG",
    "snoeifrequentie": "SNOEIFREQUENTIE",
    "theoretisch_eindjaar": "THEORETISCH_EINDJAAR",
    "oppervlakte": "OPPERVLAKTE",
    "type_bewerking": "TYPE_BEWERKING",
    "type_object": "TYPE",
    "type_object_plus": "TYPE_GEDETAILLEERD",
    "type_object_plus_2": "TYPE_EXTRA_GEDETAILLEERDE",
    "vaknummer": "VAKNUMMER",
    "object_begintijd": "VALID_FROM",
    "object_eindtijd": "VALID_TILL",
    "verwijderdatum": "VERWIJDERDATUM"
},

AssetType.VERHARDINGEN: {
    "id": "ID",
    "guid": "GUID",
    "imgeo_identificatie": "IMGEOID",
    "identificatie": "IDENTIFICATIE",
    "aantal_deklagen": "AANTAL_DEKLAGEN",
    "aantal_onderlagen": "AANTAL_ONDERLAGEN",
    "aantal_tussenlagen": "AANTAL_TUSSENLAGEN",
    "afmeting": "AFMETING",
    "bag_openbare_ruimte_naam": "OPENBARE_RUIMTE",
    "bag_woonplaats_naam": "WOONPLAATS",
    "begin_garantieperiode": "BEGIN_GARANTIEPERIODE",
    "beheergebied": "BEHEERGEBIED",
    "bergend_vermogen": "BERGEND_VERMOGEN",
    "bgt_status": "BGT_STATUS",
    "breedte": "BREEDTE",
    "brk_gme_naam": "GEMEENTE",
    "dikte_constructie": "CONSTRUCTIE",
    "datum_verwijderd": "VERWIJDERDATUM",
    "mutatiedatum": "LASTUPDATE",
    "deelsportcomplex": "DEELSPORTCOMPLEX",
    "einde_garantieperiode": "EINDE_GARANTIEPERIODE",
    "fabrikant": "FABRIKANT",
    "formaat": "FORMAAT",
    "gbd_buurt_naam": "BUURT",
    "gbd_stadsdeel_naam": "STADSDEEL_OF_KERN",
    "gbd_wijk_naam": "WIJK",
    "gebruiksfunctie": "GEBRUIKSFUNCTIE",
    "geluidsreducerend": "GELUIDSREDUCEREND",
    "jaar_conserveren": "JAAR_LAATSTE_CONSERVERING",
    "jaar_uitgevoerd_onderhoud": "JAAR_UITGEVOERD_ONDERHOUD",
    "jaar_van_aanleg": "JAAR_VAN_AANLEG",
    "kleur": "KLEUR",
    "lengte": "LENGTE",
    "materiaal": "MATERIAAL",
    "objecttype": "OBJECTTYPE",
    "onderhoudsplichtige": "ONDERHOUDSPLICHTIGE",
    "opleverdatum": "OPLEVERDATUM",
    "oppervlakte_gis": "OPPERVLAKTE_GIS",
    "relatieve_hoogteligging": "RELATIEVE_HOOGTELIGGING",
    "sportveld": "SPORTVELD",
    "theoretisch_eindjaar": "THEORETISCH_EINDJAAR",
    "type_object": "TYPE",
    "type_beheerder": "BEHEERDER",
    "type_beheerder_plus": "BEHEERDER_GEDETAILLEERD",
    "fundering": "FUNDERING",
    "type_plus": "TYPE_GEDETAILLEERD",
    "type_plus_2": "TYPE_EXTRA_GEDETAILLEERD",
    "type_rijstrook": "TYPE_RIJSTROOK",
    "waterdoorlatendheid": "WATERDOORLATENDHEID",
    "wegtype_bestaand": "WEGTYPE_BESTAAND"
}}

