gebieden = {
    "AMC": "BUURT",
    "Aalsmeerwegbuurt-Oost": "BUURT",
    "Aalsmeerwegbuurt-West": "BUURT",
    "Aetsveld-Noord": "BUURT",
    "Aetsveld-Zuid": "BUURT",
    "Aetsveldsepolder": "BUURT",
    "Afrikahaven": "BUURT",
    "Alexanderplein e.o.": "BUURT",
    "Alfa-driehoek": "BUURT",
    "Ambonpleinbuurt": "BUURT",
    "Amerikahaven": "BUURT",
    "Amstel III deel A/B-Noord": "BUURT",
    "Amstel III deel A/B-Zuid": "BUURT",
    "Amstel III deel C/D-Noord": "BUURT",
    "Amstel III deel C/D-Zuid": "BUURT",
    "Amstelglorie": "BUURT",
    "Amstelkwartier-Noord": "BUURT",
    "Amstelkwartier-West": "BUURT",
    "Amstelkwartier-Zuid": "BUURT",
    "Amstelpark": "BUURT",
    "Amstelveldbuurt": "BUURT",
    "Amsterdamse Bos": "BUURT",
    "Amsterdamse Poort": "BUURT",
    "Andreasterrein": "BUURT",
    "Anjeliersbuurt-Noord": "BUURT",
    "Anjeliersbuurt-Zuid": "BUURT",
    "Architectenbuurt": "BUURT",
    "Arondeusbuurt": "BUURT",
    "BG-terrein e.o.": "BUURT",
    "Baaibuurt-Oost": "BUURT",
    "Baaibuurt-West": "BUURT",
    "Bakemabuurt": "BUURT",
    "Balboaplein e.o.": "BUURT",
    "Banne-Noordoost": "BUURT",
    "Banne-Noordwest": "BUURT",
    "Banne-Zuidoost": "BUURT",
    "Banne-Zuidwest": "BUURT",
    "Banpleinbuurt": "BUURT",
    "Beatrixpark": "BUURT",
    "Bedrijvencentrum Osdorp": "BUURT",
    "Bedrijvencentrum Westerkwartier": "BUURT",
    "Bedrijvengebied Veelaan": "BUURT",
    "Bedrijvengebied Zeeburgerkade": "BUURT",
    "Bedrijvenpark Lutkemeer": "BUURT",
    "Bedrijventerrein Landlust": "BUURT",
    "Bedrijventerrein Nieuwendammerdijk": "BUURT",
    "Bedrijventerrein Nijverheidslaan": "BUURT",
    "Bedrijventerrein Schinkel": "BUURT",
    "Bedrijventerrein Van Houten": "BUURT",
    "Bedrijventerrein-Noord Weesp": "BUURT",
    "Beethovenbuurt": "BUURT",
    "Begijnhofbuurt": "BUURT",
    "Belgiëplein e.o.": "BUURT",
    "Bellamybuurt-Noord": "BUURT",
    "Bellamybuurt-Zuid": "BUURT",
    "Bertelmanpleinbuurt": "BUURT",
    "Betondorp": "BUURT",
    "Bijlmermuseum-Noord": "BUURT",
    "Bijlmermuseum-Zuid": "BUURT",
    "Blauwe Zand": "BUURT",
    "Bloemenbuurt-Noord": "BUURT",
    "Bloemenbuurt-Zuid": "BUURT",
    "Bloemgrachtbuurt": "BUURT",
    "Borgerbuurt": "BUURT",
    "Borneo": "BUURT",
    "Bos": None,
    "Bosleeuw": "BUURT",
    "Botteskerkbuurt": "BUURT",
    "Bovendiep/Diemerpark": "BUURT",
    "Bretten-Oost": "BUURT",
    "Bretten-West": "BUURT",
    "Buiksloterbreek": "BUURT",
    "Buiksloterdijk-Oost": "BUURT",
    "Buiksloterdijk-West": "BUURT",
    "Buiksloterham-Noord": "BUURT",
    "Buiksloterham-Zuid": "BUURT",
    "Buikslotermeer-Noord": "BUURT",
    "Buikslotermeerplein": "BUURT",
    "Buiteneiland": "BUURT",
    "Buitenveldert-Oost-Midden": "BUURT",
    "Buitenveldert-West-Midden": "BUURT",
    "Buitenveldert-Zuid-Midden": "BUURT",
    "Buitenveldert-Zuidoost": "BUURT",
    "Buitenveldert-Zuidwest": "BUURT",
    "Burgemeester Tellegenbuurt-Oost": "BUURT",
    "Burgemeester Tellegenbuurt-West": "BUURT",
    "Burgwallen-Oost": "BUURT",
    "Buyskade e.o.": "BUURT",
    "Calandlaan/Lelylaan": "BUURT",
    "Centrum": "STADSDEEL_OF_KERN",
    "Centrumeiland": "BUURT",
    "Circus/Kermisbuurt": "BUURT",
    "Coenhaven": "BUURT",
    "Columbusplein e.o.": "BUURT",
    "Concertgebouwbuurt": "BUURT",
    "Confuciusbuurt": "BUURT",
    "Contactbuurt": "BUURT",
    "Cornelis Douwesterrein-Oost": "BUURT",
    "Cornelis Douwesterrein-West": "BUURT",
    "Cornelis Schuytbuurt": "BUURT",
    "Cornelis Troostbuurt": "BUURT",
    "Coronelbuurt": "BUURT",
    "Cremerbuurt-Oost": "BUURT",
    "Cremerbuurt-West": "BUURT",
    "Cruquiusbuurt": "BUURT",
    "Czaar Peterbuurt": "BUURT",
    "D-buurt": "BUURT",
    "Da Costabuurt-Noord": "BUURT",
    "Da Costabuurt-Zuid": "BUURT",
    "Dapperbuurt-Noord": "BUURT",
    "Dapperbuurt-Zuid": "BUURT",
    "De Aker-Oost": "BUURT",
    "De Aker-West": "BUURT",
    "De Bongerd": "BUURT",
    "De Eendracht": "BUURT",
    "De Eenhoorn": "BUURT",
    "De Kameleon e.o.": "BUURT",
    "De Kleine Wereld": "BUURT",
    "De Klenckebuurt": "BUURT",
    "De Klomp": "BUURT",
    "De Omval": "BUURT",
    "De Wester Quartier": "BUURT",
    "De Wetbuurt": "BUURT",
    "De Wittenbuurt-Noord": "BUURT",
    "De Wittenbuurt-Zuid": "BUURT",
    "Delflandpleinbuurt-Oost": "BUURT",
    "Delflandpleinbuurt-West": "BUURT",
    "Den Texbuurt": "BUURT",
    "Diamantbuurt": "BUURT",
    "Dichtersbuurt": "BUURT",
    "Diepenbrockbuurt": "BUURT",
    "Dijkgraafpleinbuurt": "BUURT",
    "Dobbebuurt": "BUURT",
    "Don Bosco": "BUURT",
    "Dorp Driemond": "BUURT",
    "Dorp Sloten": "BUURT",
    "Drieburg": "BUURT",
    "Driehoekbuurt": "BUURT",
    "Dudokbuurt": "BUURT",
    "Duivelseiland": "BUURT",
    "Durgerdam": "BUURT",
    "E-buurt": "BUURT",
    "Ed Pelsterparkbuurt": "BUURT",
    "Eendrachtspark": "BUURT",
    "Elandsgrachtbuurt": "BUURT",
    "Elzenhagen-Noord": "BUURT",
    "Elzenhagen-Zuid": "BUURT",
    "Emanuel van Meterenbuurt": "BUURT",
    "Entrepot-Noordwest": "BUURT",
    "Erasmusparkbuurt-Oost": "BUURT",
    "Erasmusparkbuurt-West": "BUURT",
    "F-buurt": "BUURT",
    "Fannius Scholtenbuurt": "BUURT",
    "Felix Meritisbuurt": "BUURT",
    "Filips van Almondekwartier": "BUURT",
    "Flevopark": "BUURT",
    "Frankendael": "BUURT",
    "Frans Halsbuurt": "BUURT",
    "Frederik Hendrikbuurt-Noord": "BUURT",
    "Frederik Hendrikbuurt-Zuidoost": "BUURT",
    "Frederik Hendrikbuurt-Zuidwest": "BUURT",
    "Frederikspleinbuurt": "BUURT",
    "G-buurt-Noord": "BUURT",
    "G-buurt-Oost": "BUURT",
    "G-buurt-West": "BUURT",
    "GWL-terrein": "BUURT",
    "Gaasperpark": "BUURT",
    "Gaasperplas": "BUURT",
    "Geelvinckbuurt": "BUURT",
    "Gein 1": "BUURT",
    "Gein 2": "BUURT",
    "Gein 3": "BUURT",
    "Gein 4": "BUURT",
    "Gelderlandpleinbuurt": "BUURT",
    "Gerard Doubuurt": "BUURT",
    "Geuzenhofbuurt": "BUURT",
    "Gibraltarbuurt": "BUURT",
    "Gooise Kant": "BUURT",
    "Groenmarktkadebuurt": "BUURT",
    "Grunder/Koningshoef": "BUURT",
    "Haarlemmerbuurt-Oost": "BUURT",
    "Haarlemmerbuurt-West": "BUURT",
    "Hakfort/Huigenbos": "BUURT",
    "Hamerstraatkwartier-Oost": "BUURT",
    "Hamerstraatkwartier-West": "BUURT",
    "Harmoniehofbuurt": "BUURT",
    "Havenkwartier IJburg": "BUURT",
    "Helmersbuurt-Oost": "BUURT",
    "Hemelrijk": "BUURT",
    "Hemknoop-Noord": "BUURT",
    "Hemknoop-Zuid": "BUURT",
    "Hemonybuurt": "BUURT",
    "Hercules Seghersbuurt": "BUURT",
    "Herensingelkwartier": "BUURT",
    "Het Funen": "BUURT",
    "Hiltonbuurt": "BUURT",
    "Hoge Dijk": "BUURT",
    "Hogewey-Midden": "BUURT",
    "Hogewey-Noord": "BUURT",
    "Hogewey-Zuid": "BUURT",
    "Holendrecht-Oost": "BUURT",
    "Holendrecht-West": "BUURT",
    "Holendrecht-Zuid": "BUURT",
    "Holysloot": "BUURT",
    "Hondecoeterbuurt": "BUURT",
    "Hoofdcentrum-Zuidoost": "BUURT",
    "Hoptille": "BUURT",
    "Houthavens-Oost": "BUURT",
    "Houthavens-West": "BUURT",
    "Huntum": "BUURT",
    "IJplein e.o.": "BUURT",
    "IJsbaanpad e.o.": "BUURT",
    "IJselbuurt-Oost": "BUURT",
    "IJselbuurt-West": "BUURT",
    "Isolatorbuurt": "BUURT",
    "Jacob Geelbuurt": "BUURT",
    "Jacques Veltmanbuurt": "BUURT",
    "Jan Maijenbuurt": "BUURT",
    "Jan de Louterbuurt": "BUURT",
    "Java-eiland": "BUURT",
    "Johan Jongkindbuurt": "BUURT",
    "Johannes Vermeerbuurt": "BUURT",
    "John Franklinbuurt": "BUURT",
    "Joris Ivenspleinbuurt": "BUURT",
    "Julianapark": "BUURT",
    "K-buurt-Zuidoost": "BUURT",
    "K-buurt-Zuidwest": "BUURT",
    "KNSM-eiland": "BUURT",
    "Kadijken": "BUURT",
    "Kadoelen": "BUURT",
    "Kalverdriehoek": "BUURT",
    "Kantershof": "BUURT",
    "Kattenburg": "BUURT",
    "Kazernebuurt": "BUURT",
    "Kelbergen": "BUURT",
    "Klaprozenbuurt": "BUURT",
    "Kolenkitbuurt-Noord": "BUURT",
    "Kolenkitbuurt-Zuid": "BUURT",
    "Koningin Wilhelminaplein": "BUURT",
    "Kop Zeedijk": "BUURT",
    "Kop Zuidas": "BUURT",
    "Kortenaerkwartier": "BUURT",
    "Kortvoort": "BUURT",
    "Kromme Mijdrechtbuurt": "BUURT",
    "L-buurt": "BUURT",
    "Laan van Spartaan": "BUURT",
    "Landelijk gebied Driemond": "BUURT",
    "Landlust-Noord": "BUURT",
    "Landlust-Zuid": "BUURT",
    "Lanenrijk": "BUURT",
    "Langestraat e.o.": "BUURT",
    "Lastage": "BUURT",
    "Leeuwenveld": "BUURT",
    "Legmeerpleinbuurt": "BUURT",
    "Leidsebuurt-Noordoost": "BUURT",
    "Leidsebuurt-Noordwest": "BUURT",
    "Leidsebuurt-Zuidoost": "BUURT",
    "Leidsebuurt-Zuidwest": "BUURT",
    "Leidsegracht-Noord": "BUURT",
    "Leidsegracht-Zuid": "BUURT",
    "Leliegracht e.o.": "BUURT",
    "Linnaeusparkbuurt": "BUURT",
    "Lizzy Ansinghbuurt": "BUURT",
    "Lodewijk van Deysselbuurt": "BUURT",
    "Loenermark": "BUURT",
    "Lootsbuurt": "BUURT",
    "Louis Couperusbuurt": "BUURT",
    "Louis Crispijnbuurt": "BUURT",
    "Lucas/Andreasziekenhuis e.o.": "BUURT",
    "Makassarpleinbuurt": "BUURT",
    "Marathonbuurt-Oost": "BUURT",
    "Marathonbuurt-West": "BUURT",
    "Marcanti": "BUURT",
    "Marine-Etablissement": "BUURT",
    "Marjoleinterrein": "BUURT",
    "Markengouw-Midden": "BUURT",
    "Markengouw-Noord": "BUURT",
    "Markengouw-Zuid": "BUURT",
    "Markthallen": "BUURT",
    "Marnixbuurt-Midden": "BUURT",
    "Marnixbuurt-Noord": "BUURT",
    "Marnixbuurt-Zuid": "BUURT",
    "Medisch Centrum Slotervaart": "BUURT",
    "Meer en Oever": "BUURT",
    "Meerwaldtbuurt": "BUURT",
    "Melkweg/Oostzanerwerf": "BUURT",
    "Mercatorpark": "BUURT",
    "Middelveldsche Akerpolder": "BUURT",
    "Middenmeer-Noord": "BUURT",
    "Middenmeer-Zuid": "BUURT",
    "Minervabuurt-Midden": "BUURT",
    "Minervabuurt-Noord": "BUURT",
    "Minervabuurt-Zuid": "BUURT",
    "Minervahaven-Noordoost": "BUURT",
    "Minervahaven-Noordwest": "BUURT",
    "Minervahaven-Zuidoost": "BUURT",
    "Minervahaven-Zuidwest": "BUURT",
    "Molenwijk": "BUURT",
    "Muidenbuurt-Oost": "BUURT",
    "Muidenbuurt-West": "BUURT",
    "Museumplein": "BUURT",
    "NDSM terrein": "BUURT",
    "Nelson Mandelapark": "BUURT",
    "Nes e.o.": "BUURT",
    "Nieuw-Sloten-Noordoost": "BUURT",
    "Nieuw-Sloten-Noordwest": "BUURT",
    "Nieuw-Sloten-Zuidoost": "BUURT",
    "Nieuw-Sloten-Zuidwest": "BUURT",
    "Nieuw-West": "STADSDEEL_OF_KERN",
    "Nieuwe Kerk e.o.": "BUURT",
    "Nieuwe Meer": "BUURT",
    "Nieuwe Oosterbegraafplaats": "BUURT",
    "Nieuwendammerdijk-Oost": "BUURT",
    "Nieuwendammerdijk-West": "BUURT",
    "Nieuwendammerdijk-Zuid": "BUURT",
    "Nieuwendijk-Noord": "BUURT",
    "Nieuwmarkt": "BUURT",
    "Nintemanterrein": "BUURT",
    "Noord": "STADSDEEL_OF_KERN",
    "Noorder IJplas": "BUURT",
    "Noorderstrook-Oost": "BUURT",
    "Noorderstrook-West": "BUURT",
    "Noordoever Sloterplas": "BUURT",
    "Olympisch Stadion e.o.": "BUURT",
    "Ookmeer": "BUURT",
    "Oost": "STADSDEEL_OF_KERN",
    "Oostelijke Handelskade": "BUURT",
    "Oostelijke Vechtoever": "BUURT",
    "Oostenburg": "BUURT",
    "Oosterdokseiland": "BUURT",
    "Oosterpark": "BUURT",
    "Oosterparkbuurt-Noordwest": "BUURT",
    "Oosterparkbuurt-Zuidoost": "BUURT",
    "Oosterparkbuurt-Zuidwest": "BUURT",
    "Oostoever Sloterplas": "BUURT",
    "Oostpoort": "BUURT",
    "Oostpunt Zeeburgereiland": "BUURT",
    "Oostzanerdijk": "BUURT",
    "Orteliusbuurt-Midden": "BUURT",
    "Orteliusbuurt-Noord": "BUURT",
    "Orteliusbuurt-Zuid": "BUURT",
    "Osdorp-Zuidoost": "BUURT",
    "Osdorper Binnenpolder": "BUURT",
    "Osdorper Bovenpolder": "BUURT",
    "Osdorpplein e.o.": "BUURT",
    "Oude Kerk e.o.": "BUURT",
    "Overamstel": "BUURT",
    "Overbraker Binnenpolder": "BUURT",
    "Overhoeks": "BUURT",
    "Overtoomse Veld-Noord": "BUURT",
    "Overtoomse Veld-Zuid": "BUURT",
    "P.C. Hooftbuurt": "BUURT",
    "Pampusbuurt-Oost": "BUURT",
    "Pampusbuurt-West": "BUURT",
    "Paramariboplein e.o.": "BUURT",
    "Park Haagseweg": "BUURT",
    "Park de Meer": "BUURT",
    "Parooldriehoek": "BUURT",
    "Passeerdersgrachtbuurt": "BUURT",
    "Petroleumhaven": "BUURT",
    "Pieter van der Doesbuurt": "BUURT",
    "Plan van Gool": "BUURT",
    "Planciusbuurt-Noord": "BUURT",
    "Planciusbuurt-Zuid": "BUURT",
    "Plantage": "BUURT",
    "Postjeskade e.o.": "BUURT",
    "Prinses Irenebuurt": "BUURT",
    "RAI": "BUURT",
    "Ransdorp": "BUURT",
    "Rapenburg": "BUURT",
    "Rechte H-buurt": "BUURT",
    "Reigersbos 1": "BUURT",
    "Reigersbos 2": "BUURT",
    "Reigersbos 3": "BUURT",
    "Reigersbos 4": "BUURT",
    "Reimerswaal": "BUURT",
    "Rembrandtpark-Noord": "BUURT",
    "Rembrandtpark-Zuid": "BUURT",
    "Rembrandtplein e.o.": "BUURT",
    "Riekerhaven": "BUURT",
    "Riekerpolder": "BUURT",
    "Rieteiland-Oost": "BUURT",
    "Rieteilanden-West": "BUURT",
    "Rietlanden": "BUURT",
    "Rijnbuurt-Midden": "BUURT",
    "Rijnbuurt-Oost": "BUURT",
    "Rijnbuurt-West": "BUURT",
    "Robert Scottbuurt-Oost": "BUURT",
    "Robert Scottbuurt-West": "BUURT",
    "Rode Kruisbuurt": "BUURT",
    "Ruys de Beerenbrouckbuurt": "BUURT",
    "Sarphatiparkbuurt": "BUURT",
    "Sarphatistrook": "BUURT",
    "Scheepvaarthuisbuurt": "BUURT",
    "Scheldebuurt-Midden": "BUURT",
    "Scheldebuurt-Oost": "BUURT",
    "Scheldebuurt-West": "BUURT",
    "Schellingwoude-Noord": "BUURT",
    "Schellingwoude-Oost": "BUURT",
    "Schellingwoude-West": "BUURT",
    "Schinkelbuurt-Noord": "BUURT",
    "Schinkelbuurt-Zuid": "BUURT",
    "Schipluidenbuurt": "BUURT",
    "Science Park-Noord": "BUURT",
    "Science Park-Zuid": "BUURT",
    "Sloterdijk De Heining": "BUURT",
    "Sloterdijk Donauhoek": "BUURT",
    "Sloterdijk Poort-Noord": "BUURT",
    "Sloterdijk Poort-Zuid": "BUURT",
    "Sloterdijk Rhônepark": "BUURT",
    "Sloterdijk Stationskwartier": "BUURT",
    "Sloterpark": "BUURT",
    "Sloterweg e.o.": "BUURT",
    "Sluisbuurt": "BUURT",
    "Spaarndammerbuurt-Midden": "BUURT",
    "Spaarndammerbuurt-Noordoost": "BUURT",
    "Spaarndammerbuurt-Noordwest": "BUURT",
    "Spaarndammerbuurt-Zuidoost": "BUURT",
    "Spaarndammerbuurt-Zuidwest": "BUURT",
    "Spiegelbuurt": "BUURT",
    "Sporenburg": "BUURT",
    "Sportheldenbuurt": "BUURT",
    "Sportpark Middenmeer-Noord": "BUURT",
    "Sportpark Middenmeer-Zuid": "BUURT",
    "Sportpark Voorland": "BUURT",
    "Spuistraat-Noord": "BUURT",
    "Spuistraat-Zuid": "BUURT",
    "Staalmanbuurt": "BUURT",
    "Staatsliedenbuurt-Noordoost": "BUURT",
    "Stationsplein e.o.": "BUURT",
    "Steigereiland-Noord": "BUURT",
    "Steigereiland-Zuid": "BUURT",
    "Sumatraplantsoenbuurt": "BUURT",
    "Surinamepleinbuurt": "BUURT",
    "Terrasdorp": "BUURT",
    "Theo van Goghparkbuurt": "BUURT",
    "Timorpleinbuurt-Noord": "BUURT",
    "Timorpleinbuurt-Zuid": "BUURT",
    "Transvaalbuurt-Oost": "BUURT",
    "Transvaalbuurt-West": "BUURT",
    "Trompbuurt": "BUURT",
    "Tuindorp Amstelstation": "BUURT",
    "Tuindorp Frankendael": "BUURT",
    "Tuindorp Nieuwendam-Oost": "BUURT",
    "Tuindorp Nieuwendam-West": "BUURT",
    "Tuindorp Oostzaan-Oost": "BUURT",
    "Tuindorp Oostzaan-West": "BUURT",
    "Twiske-Oost": "BUURT",
    "Twiske-West": "BUURT",
    "Uilenburg": "BUURT",
    "Utrechtsebuurt-Zuid": "BUURT",
    "VU-kwartier": "BUURT",
    "Valeriusbuurt-Oost": "BUURT",
    "Valeriusbuurt-West": "BUURT",
    "Valkenburg": "BUURT",
    "Van Brakelkwartier": "BUURT",
    "Van Tijenbuurt": "BUURT",
    "Van Tuyllbuurt": "BUURT",
    "Van der Helstpleinbuurt": "BUURT",
    "Van der Kunbuurt": "BUURT",
    "Van der Pekbuurt": "BUURT",
    "Vechtrijk": "BUURT",
    "Veluwebuurt": "BUURT",
    "Venserpolder-Oost": "BUURT",
    "Venserpolder-West": "BUURT",
    "Vervoerscentrum": "BUURT",
    "Vijzelstraatbuurt": "BUURT",
    "Vivaldi": "BUURT",
    "Vliegenbos": "BUURT",
    "Vlothaven": "BUURT",
    "Vogelbuurt-Noord": "BUURT",
    "Vogelbuurt-Zuid": "BUURT",
    "Vogeltjeswei": "BUURT",
    "Vondelpark-Oost": "BUURT",
    "Vondelpark-West": "BUURT",
    "Vondelparkbuurt-Midden": "BUURT",
    "Vondelparkbuurt-Oost": "BUURT",
    "Vondelparkbuurt-West": "BUURT",
    "WG-terrein": "BUURT",
    "Walvisbuurt": "BUURT",
    "Waterloopleinbuurt": "BUURT",
    "Waterrijk": "BUURT",
    "Weesp": "STADSDEEL_OF_KERN",
    "Weesp Centrum": "BUURT",
    "Weesp Dichtersbuurt": "BUURT",
    "Weesp Schildersbuurt": "BUURT",
    "Weesp-Zuid I": "BUURT",
    "Weesp-Zuid II": "BUURT",
    "Weesperbuurt": "BUURT",
    "Weespersluis-Noord": "BUURT",
    "Weespertrekvaart": "BUURT",
    "Weesperzijde-Midden/Zuid": "BUURT",
    "Weesperzijde-Noord": "BUURT",
    "Wegener Sleeswijkbuurt": "BUURT",
    "Werengouw-Midden": "BUURT",
    "Werengouw-Noord": "BUURT",
    "Werengouw-Zuid": "BUURT",
    "West": "STADSDEEL_OF_KERN",
    "Westelijke eilanden": "BUURT",
    "Westerdokseiland": "BUURT",
    "Westergasfabriek": "BUURT",
    "Westerstaatsman": "BUURT",
    "Westhaven-Noord": "BUURT",
    "Westhaven-Zuid": "BUURT",
    "Westlandgrachtbuurt": "BUURT",
    "Westpoort": "STADSDEEL_OF_KERN",
    "Weteringbuurt": "BUURT",
    "Wielingenbuurt": "BUURT",
    "Wildeman": "BUURT",
    "Willemsparkbuurt-Noord": "BUURT",
    "Willibrordusbuurt": "BUURT",
    "Wittenburg": "BUURT",
    "Woon- en Groengebied Sloterdijk": "BUURT",
    "Zaagpoortbuurt": "BUURT",
    "Zaanstraat emplacement": "BUURT",
    "Zeeburgerdijk-Oost": "BUURT",
    "Zeeheldenbuurt": "BUURT",
    "Zorgvlied": "BUURT",
    "Zuid": "STADSDEEL_OF_KERN",
    "Zuidas-Noord": "BUURT",
    "Zuidas-Zuid": "BUURT",
    "Zuiderhof": "BUURT",
    "Zuiderkerkbuurt": "BUURT",
    "Zuidoost": "STADSDEEL_OF_KERN",
    "Zuidwestkwadrant-Noord": "BUURT",
    "Zuidwestkwadrant-Zuid": "BUURT",
    "Zunderdorp": "BUURT",
    "Zwarte Gouw": "BUURT",
}
